server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location = /local-style.json {
        root /usr/share/nginx/html;
        sub_filter_types application/json;
        sub_filter '"url":"/sprites/basics/sprites"' '"url":"http://$http_host/sprites/basics/sprites"';
        sub_filter '"glyphs":"/fonts/{fontstack}/{range}.pbf"' '"glyphs":"http://$http_host/fonts/{fontstack}/{range}.pbf"';
        sub_filter '"tiles":["/tiles/osm/{z}/{x}/{y}"]' '"tiles":["http://$http_host/tiles/osm/{z}/{x}/{y}"]';
        sub_filter_once off;
    }

    location /routing/ {
        proxy_pass http://mapstack:80/routing/;
    }

    # graphhopper-maps hardcodes the "geocode" endpoint name; Photon exposes it as "api"
    location /geocode/geocode {
        proxy_pass http://mapstack:80/geocode/api;
    }

    location /geocode/ {
        proxy_pass http://mapstack:80/geocode/;
    }

    location /tiles/ {
        proxy_pass http://mapstack:80/tiles/;
    }

    location /sprites/ {
        proxy_pass http://mapstack:80/sprites/;
    }

    location /fonts/ {
        proxy_pass http://mapstack:80/fonts/;
    }
}
